const reviewsData = [
  { name: "jess_r", rating: 5, tags: ["strawberry", "houston"], comment: "honestly these strawberries are so clutch. lowkey obsessed w/ the texture, they have this crazy good crunch. finished the whole bag in like 10 mins tbh", date: "2 days ago" },
  { name: "Caleb Vance", rating: 5, tags: ["banana", "ut"], comment: "tbh the chocolate bananas are actually gas. way cheaper than the campus store vending machines and perfect to keep in my dorm fridge", date: "3 days ago" },
  { name: "Sarah M.", rating: 5, tags: ["mango"], comment: "mango and milk chocolate is a combo i didn't know i needed. lowkey vibes", date: "4 days ago" },
  { name: "Brandon K.", rating: 5, tags: ["ut"], comment: "lowkey obsessed w/ the strawberry mix. the crunch w/ the milk chocolate is so good when studying at pcl at 2am", date: "5 days ago" },
  { name: "josh_t", rating: 5, tags: ["blueberry"], comment: "the blueberries are fully coated which is a huge win. crunchy, sweet, rich chocolate. clutch late night snack", date: "6 days ago" },
  { name: "Elena Gonzalez", rating: 5, tags: ["all"], comment: "is it healthy? yes, fruit. is it chocolate? yes. therefore it is the perfect study snack. tbh i'm hooked", date: "1 week ago" },
  { name: "Ryan Parker", rating: 5, tags: ["houston"], comment: "timothy and michael are super chill, texted them to order and got it the next day. pretty good service", date: "2 days ago" },
  { name: "Taylor S.", rating: 5, tags: ["ut"], comment: "stats major michael did the math bc the chocolate to crunch ratio is actually perfect. lowkey a lifesaver during midterms week", date: "3 days ago" },
  { name: "Megan Patel", rating: 5, tags: ["strawberry", "banana"], comment: "crunch level 100. strawberry and milk chocolate combo never fails. banana is pretty good too", date: "4 days ago" },
  { name: "dylan.w", rating: 4, tags: ["mango", "apple"], comment: "really solid, mango chunks are awesome. apple is super crispy. wish there were a few more apples in my bag but overall pretty good tbh", date: "5 days ago" },
  { name: "Chloe L.", rating: 5, tags: ["blueberry", "houston"], comment: "the blueberries are tiny pops of absolute heaven. perfect for studying. houston delivery was quick", date: "6 days ago" },
  { name: "Matt H.", rating: 5, tags: ["all"], comment: "the texture is unreal. it has this light airy snap to it and then the rich milk chocolate hits. 5 stars. lowkey clutch", date: "1 week ago" },
  { name: "Sofia Alvarez", rating: 5, tags: ["mango"], comment: "golden mango chunks are the best part tbh. feels like a tropical treat but elevated. pretty good", date: "2 days ago" },
  { name: "Will G.", rating: 5, tags: ["ut"], comment: "my roommate brought a bag to the dorm and i ate the whole thing in like 2 mins bc the apple crunch is insane. actually gas", date: "3 days ago" },
  { name: "Rachel Jenkins", rating: 5, tags: ["houston"], comment: "so crispy!! and the chocolate isn't overly sweet. milk chocolate is definitely the way to go. clutch for library sessions", date: "4 days ago" },
  { name: "devon_codes", rating: 5, tags: ["ut"], comment: "clutch study snack for final exams. the chocolate strawberries are so crispy and not soggy at all. lowkey obsessed", date: "5 days ago" },
  { name: "Emily K.", rating: 5, tags: ["banana"], comment: "honestly hated dried banana before this. the freeze dried texture is totally different. it melts in your mouth with the chocolate. love it", date: "6 days ago" },
  { name: "Justin Lee", rating: 5, tags: ["houston"], comment: "pickup in Houston was seamless. they literally hand-dipped it a day before. you can taste the quality. pretty good tbh", date: "1 week ago" },
  { name: "Hannah B.", rating: 5, tags: ["strawberry"], comment: "the strawberries are enormous! half-dipped looks so pretty too, perfect for gifting. lowkey vibes", date: "2 days ago" },
  { name: "Marcus", rating: 5, tags: ["all"], comment: "best late night study snack. doesn't leave grease on my keyboard and gives me a quick sugar kick without crash", date: "3 days ago" },
  { name: "lauren_p", rating: 4, tags: ["apple"], comment: "very crispy apple slices! tastes like apple pie but with milk chocolate. pretty good tbh", date: "4 days ago" },
  { name: "Daniel Kim", rating: 5, tags: ["ut"], comment: "biochem major here and the chocolate temper on the bananas is perfect. doesn't melt all over my notes while i'm studying", date: "5 days ago" },
  { name: "Sam Vance", rating: 5, tags: ["houston"], comment: "only $5 a bag for artisanal hand dipped fruit is crazy. local businesses over corporations any day. clutch price", date: "6 days ago" },
  { name: "Olivia_R", rating: 5, tags: ["all"], comment: "literally obsessed. i've bought 6 bags already and shared them with my office. everyone is hooked. lowkey elite", date: "1 week ago" },
  { name: "Zack", rating: 5, tags: ["strawberry", "blueberry"], comment: "strawberry and blueberry combo is elite. bag was gone in one sitting. pretty good tbh", date: "2 days ago" },
  { name: "Nicole W.", rating: 5, tags: ["mango"], comment: "mango is literally so sweet and tropical. perfect balance with the milk chocolate. lowkey clutch", date: "3 days ago" },
  { name: "kyle_r", rating: 5, tags: ["ut"], comment: "hook em! these are so good to throw in my backpack before class. way better than paying $4 for a trash vending machine snack", date: "4 days ago" },
  { name: "Grace Fletcher", rating: 5, tags: ["houston"], comment: "Timothy and Michael are doing an amazing job. Highly recommend supporting these Houston locals.", date: "5 days ago" },
  { name: "Tyler Brooks", rating: 5, tags: ["banana"], comment: "banana crunch is unreal. it's like eating banana bread but crispy and cold. pretty good tbh", date: "6 days ago" },
  { name: "Hailey M.", rating: 5, tags: ["all"], comment: "so good. love that it's just real fruit and milk chocolate. no weird chemicals", date: "1 week ago" },
  { name: "Austin Snacker", rating: 5, tags: ["ut"], comment: "tbh i was skeptical bc healthy snacks are usually mid but the strawberry crunch is actually gas. perfect dorm snack", date: "2 days ago" },
  { name: "Maria S.", rating: 5, tags: ["strawberry"], comment: "the strawberries are so tart and contrast so well with the milk chocolate. pretty good tbh", date: "3 days ago" },
  { name: "Jared P.", rating: 4, tags: ["all"], comment: "really good mix. blueberries are tiny but super packed with flavor. solid 4.5/5. pretty good tbh", date: "4 days ago" },
  { name: "Lily T.", rating: 5, tags: ["houston"], comment: "texted them to order and got a reply in 2 minutes. easiest transaction ever. snack is fire. clutch", date: "5 days ago" },
  { name: "Nate_D", rating: 5, tags: ["blueberry"], comment: "fully coated blueberries are dangerous. i ate the whole bag without realizing. lowkey elite", date: "6 days ago" },
  { name: "Vanessa", rating: 5, tags: ["apple"], comment: "crisp apple is actually my favorite. reminds me of autumn caramel apples but better and healthier. pretty good", date: "1 week ago" },
  { name: "Ian", rating: 5, tags: ["ut"], comment: "perfect mix of sweet and crunch for late night library grinds. the apple slices w/ milk chocolate are so clutch rn", date: "2 days ago" },
  { name: "Courtney B.", rating: 5, tags: ["houston"], comment: "houston has some great local food, and dippd is definitely one of them. support local! pretty good", date: "3 days ago" },
  { name: "Luke Williams", rating: 5, tags: ["all"], comment: "hands down the best snack of the year. the freeze dried crunch is so satisfying. lowkey clutch", date: "4 days ago" },
  { name: "Siddharth", rating: 5, tags: ["ut"], comment: "lowkey obsessed w/ the mango slices. perfect sweet kick when i'm dying in the library studying for finals", date: "5 days ago" },
  { name: "Emma Watson", rating: 5, tags: ["strawberry"], comment: "the strawberries are literally perfect. i wish i could buy a bag of just strawberries too! pretty good tbh", date: "6 days ago" },
  { name: "Gavin", rating: 5, tags: ["banana"], comment: "obsessed with the banana slices. creamy chocolate and sweet airy banana. lowkey vibes", date: "1 week ago" },
  { name: "Natalie", rating: 5, tags: ["mango"], comment: "mango is so juicy-tasting even though it's freeze dried. love the milk chocolate half-dip. pretty good", date: "2 days ago" },
  { name: "Alex K.", rating: 5, tags: ["houston"], comment: "amazing product, amazing founders. houston local delivery was super friendly. clutch", date: "3 days ago" },
  { name: "Brooke", rating: 5, tags: ["all"], comment: "perfect portion, perfect crunch, perfect sweetness. literally zero complaints. lowkey elite", date: "4 days ago" },
  { name: "Jeremy", rating: 5, tags: ["ut"], comment: "cheaper than the campus store and actually tastes premium. the strawberry and milk chocolate mix is elite tbh", date: "5 days ago" },
  { name: "Isabella", rating: 5, tags: ["houston"], comment: "tastes like something you'd get at a high-end boutique but for only $5. crazy value. clutch price", date: "6 days ago" },
  { name: "Peter P.", rating: 5, tags: ["blueberry"], comment: "coated blueberries are the goat. period.", date: "1 week ago" },
  { name: "Rachel", rating: 5, tags: ["all"], comment: "so addictive. i bought three bags and they didn't survive the weekend. lowkey elite", date: "2 days ago" },
  { name: "Aaron", rating: 5, tags: ["ut"], comment: "so clutch for class. the banana crunch w/ chocolate is crazy good. bought 2 bags bc i knew i'd eat it all instantly", date: "3 days ago" },
  { name: "Katie S.", rating: 5, tags: ["strawberry"], comment: "the strawberry slices are gigantic. delicious milk chocolate. pretty good tbh", date: "4 days ago" },
  { name: "Mrs. Henderson", rating: 5, tags: ["strawberry", "houston"], comment: "Highly recommend! The chocolate-covered strawberries are a huge hit in our house... GREAT quality milk chocolate and perfect crunch. Such a clean treat!", date: "5 days ago" },
  { name: "Debbie L.", rating: 5, tags: ["banana"], comment: "My kids love the banana slices!!! Perfect for packing in their school lunches... Excellent milk chocolate temper too, doesn't melt in their hands instantly. Life saver!", date: "6 days ago" },
  { name: "Robert M.", rating: 5, tags: ["mango"], comment: "Absolute Life saver for after school snacks!!! My kids love the mango chunks and I feel good knowing it is just real fruit and milk chocolate... Worth every penny, ordering two more bags today!", date: "1 week ago" },
  { name: "Karen T.", rating: 5, tags: ["houston"], comment: "GREAT customer service! Timothy and Michael were so polite when delivering our order in Houston. Highly recommend supporting these longhorns!", date: "2 days ago" },
  { name: "Linda G.", rating: 5, tags: ["all"], comment: "Worth every penny... The freeze dried strawberries have such a wonderful crunch. My kids devoured them in minutes! We will definitely be regular customers!", date: "3 days ago" },
  { name: "Mark S.", rating: 5, tags: ["ut"], comment: "So proud of these student entrepreneurs! My daughter goes to UT and brought some home for us... My kids love it! Highly recommend!", date: "4 days ago" },
  { name: "Patricia K.", rating: 5, tags: ["houston"], comment: "Life saver for our busy soccer weekends... Easy to pack, no mess, and the kids think they are getting a dessert! Perfect balance of healthy fruit and premium chocolate!", date: "5 days ago" },
  { name: "Elizabeth_snack_mom", rating: 5, tags: ["all"], comment: "highly recommend the mix bag... You get all 5 fruits and it is a GREAT way to see what your family likes best. The apple slices are absolutely delicious!", date: "6 days ago" },
  { name: "Thomas Brooks", rating: 5, tags: ["banana"], comment: "So hard to find snacks that my kids agree on, but they both went crazy for the banana! GREAT quality product. Worth every penny!", date: "1 week ago" },
  { name: "Sandra M.", rating: 5, tags: ["mango"], comment: "Such a lovely local Houston business... Hand-dipped and you can really tell the difference in quality... Highly recommend!", date: "2 days ago" },
  { name: "Jessica F.", rating: 5, tags: ["houston"], comment: "What a fantastic treat! The mango slices are so sweet and the milk chocolate coating is outstanding... GREAT flavor combination. My husband and kids love it!", date: "3 days ago" },
  { name: "Carol D.", rating: 5, tags: ["all"], comment: "Life saver for road trips... No sticky fingers because of the excellent dipping technique! Highly recommend to all parents!", date: "4 days ago" },
  { name: "Richard P.", rating: 5, tags: ["ut"], comment: "We bought 4 bags for a birthday party and the kids ate them all... GREAT healthy alternative to candy! Worth every penny!", date: "5 days ago" },
  { name: "Susan Vance", rating: 5, tags: ["houston"], comment: "Worth every penny! I love that there are no artificial preservatives or dyes... Just real fruit and excellent milk chocolate. Highly recommend!", date: "6 days ago" },
  { name: "Barbara", rating: 5, tags: ["all"], comment: "Highly recommend for anyone with toddlers! It is a GREAT way to get them to eat fruit... My kids love it so much!", date: "1 week ago" },
  { name: "Josephine R.", rating: 5, tags: ["strawberry"], comment: "The strawberries are so fresh and sweet... Absolutely worth every penny... Highly recommend to everyone!", date: "2 days ago" },
  { name: "Margaret L.", rating: 5, tags: ["banana"], comment: "Life saver for morning school prep! Just toss a bag in their backpack... GREAT texture and taste!", date: "3 days ago" },
  { name: "Charles S.", rating: 5, tags: ["mango"], comment: "Outstanding local business! We got our delivery yesterday and my kids have already finished two bags... Highly recommend!", date: "4 days ago" },
  { name: "Dorothy B.", rating: 5, tags: ["houston"], comment: "So glad to support Michael and Timothy... GREAT customer service and the chocolate fruit is delicious... Worth every penny!", date: "5 days ago" },
  { name: "Christopher", rating: 5, tags: ["all"], comment: "Highly recommend the Dippd mix. It has a GREAT variety of fruits... Worth every penny for a clean family treat!", date: "6 days ago" },
  { name: "Nancy", rating: 5, tags: ["ut"], comment: "Hook em! My son bought this on campus and sent it home... Highly recommend! Worth every penny!", date: "1 week ago" },
  { name: "Helen", rating: 5, tags: ["houston"], comment: "Wonderful quality fruit! The milk chocolate is very rich... My kids love it for an evening treat... Highly recommend!", date: "2 days ago" },
  { name: "Edward J.", rating: 5, tags: ["all"], comment: "GREAT product for active kids. Perfect to bring to soccer games... Worth every penny!", date: "3 days ago" },
  { name: "Betty", rating: 5, tags: ["strawberry"], comment: "The strawberries are sweet and tart... Highly recommend for a healthy dessert option... Worth every penny!", date: "4 days ago" },
  { name: "Ronald", rating: 5, tags: ["banana"], comment: "My kids love the banana flavor... Excellent milk chocolate! We will definitely buy regularly... Highly recommend!", date: "5 days ago" },
  { name: "Lisa_H", rating: 5, tags: ["mango"], comment: "Life saver for after school cravings... GREAT tasting mango and milk chocolate... Worth every penny!", date: "6 days ago" },
  { name: "Donald", rating: 5, tags: ["houston"], comment: "Excellent local Houston business. GREAT communication and delivery... Highly recommend!", date: "1 week ago" },
  { name: "George", rating: 5, tags: ["all"], comment: "Highly recommend! The chocolate-covered strawberries are a huge hit in our house... GREAT quality milk chocolate and perfect crunch. Such a clean treat!", date: "2 days ago" },
  { name: "Kenneth", rating: 5, tags: ["ut"], comment: "Hook em! Supporting student startups is so important... My kids love it! Highly recommend!", date: "3 days ago" },
  { name: "Sue", rating: 5, tags: ["houston"], comment: "Worth every penny... The freeze dried strawberries have such a wonderful crunch. My kids devoured them in minutes! We will definitely be regular customers!", date: "4 days ago" },
  { name: "Steven", rating: 5, tags: ["all"], comment: "Life saver for road trips... No sticky fingers because of the excellent dipping technique! Highly recommend to all parents!", date: "5 days ago" },
  { name: "Edward J.", rating: 5, tags: ["strawberry"], comment: "highly recommend the mix bag... You get all 5 fruits and it is a GREAT way to see what your family likes best. The apple slices are absolutely delicious!", date: "6 days ago" },
  { name: "Betty", rating: 5, tags: ["banana"], comment: "So hard to find snacks that my kids agree on, but they both went crazy for the banana! GREAT quality product. Worth every penny!", date: "1 week ago" },
  { name: "Ronald", rating: 5, tags: ["mango"], comment: "Such a lovely local Houston business... Hand-dipped and you can really tell the difference in quality... Highly recommend!", date: "2 days ago" },
  { name: "Lisa_H", rating: 5, tags: ["houston"], comment: "What a fantastic treat! The mango slices are so sweet and the milk chocolate coating is outstanding... GREAT flavor combination. My husband and kids love it!", date: "3 days ago" },
  { name: "Donald", rating: 5, tags: ["all"], comment: "We bought 4 bags for a birthday party and the kids ate them all... GREAT healthy alternative to candy! Worth every penny!", date: "4 days ago" },
  { name: "George", rating: 5, tags: ["ut"], comment: "Worth every penny! I love that there are no artificial preservatives or dyes... Just real fruit and excellent milk chocolate. Highly recommend!", date: "5 days ago" },
  { name: "Kenneth", rating: 5, tags: ["houston"], comment: "Highly recommend for anyone with toddlers! It is a GREAT way to get them to eat fruit... My kids love it so much!", date: "6 days ago" },
  { name: "Sue", rating: 5, tags: ["all"], comment: "The strawberries are so fresh and sweet... Absolutely worth every penny... Highly recommend to everyone!", date: "1 week ago" },
  { name: "Steven", rating: 5, tags: ["strawberry"], comment: "Life saver for morning school prep! Just toss a bag in their backpack... GREAT texture and taste!", date: "2 days ago" },
  { name: "Edward J.", rating: 5, tags: ["banana"], comment: "Outstanding local business! We got our delivery yesterday and my kids have already finished two bags... Highly recommend!", date: "3 days ago" },
  { name: "Betty", rating: 5, tags: ["mango"], comment: "So glad to support Michael and Timothy... GREAT customer service and the chocolate fruit is delicious... Worth every penny!", date: "4 days ago" },
  { name: "Ronald", rating: 5, tags: ["houston"], comment: "Highly recommend the Dippd mix. It has a GREAT variety of fruits... Worth every penny for a clean family treat!", date: "5 days ago" },
  { name: "Lisa_H", rating: 5, tags: ["all"], comment: "Hook em! My son bought this on campus and sent it home... Highly recommend! Worth every penny!", date: "6 days ago" },
  { name: "Donald", rating: 5, tags: ["strawberry"], comment: "Wonderful quality fruit! The milk chocolate is very rich... My kids love it for an evening treat... Highly recommend!", date: "1 week ago" },
  { name: "George", rating: 5, tags: ["banana"], comment: "GREAT product for active kids. Perfect to bring to soccer games... Worth every penny!", date: "2 days ago" },
  { name: "Kenneth", rating: 5, tags: ["mango"], comment: "The strawberries are sweet and tart... Highly recommend for a healthy dessert option... Worth every penny!", date: "3 days ago" },
  { name: "Sue", rating: 5, tags: ["houston"], comment: "My kids love the banana flavor... Excellent milk chocolate! We will definitely buy regularly... Highly recommend!", date: "4 days ago" },
  { name: "Steven", rating: 5, tags: ["all"], comment: "Life saver for after school cravings... GREAT tasting mango and milk chocolate... Worth every penny!", date: "5 days ago" },
  { name: "Edward J.", rating: 5, tags: ["strawberry"], comment: "Excellent local Houston business. GREAT communication and delivery... Highly recommend!", date: "6 days ago" },
  { name: "Betty", rating: 5, tags: ["banana"], comment: "Highly recommend! The chocolate-covered blueberries are a huge hit in our house... GREAT quality milk chocolate and perfect crunch. Such a clean treat!", date: "1 week ago" },
  { name: "Audrey", rating: 5, tags: ["houston"], comment: "Such a lovely local Houston business... Hand-dipped and you can really tell the difference in quality... Highly recommend!", date: "2 days ago" }
];
